import type { Metadata } from "next"
import Head from "next/head"
import { Shield } from "lucide-react" // Import the Shield component

interface Props {
    params: Promise<{ uuid: string }>
}

export async function generateMetadata({ params }: Props): Promise<Metadata> {
    const { uuid } = await params

    return {
        title: "Health Insurance Recommendations - Shared Report | TryZent AI",
        description:
            "View personalized health insurance plan recommendations generated by AI. Compare coverage options, costs, and find the perfect plan for your needs.",
        keywords: [
            "health insurance",
            "insurance comparison",
            "coverage analysis",
            "AI recommendations",
            "health plans",
            "insurance finder",
            "medical coverage",
            "insurance quotes",
            "health benefits",
            "insurance marketplace",
        ],
        authors: [{ name: "TryZent" }],
        creator: "TryZent",
        publisher: "TryZent",
        robots: "index, follow",
        openGraph: {
            title: "AI-Generated Health Insurance Recommendations",
            description:
                "Personalized health insurance plan analysis with coverage comparison, cost breakdown, and expert recommendations.",
            type: "article",
            url: `https://agents.tryzent.com/share/health-insurance-finder/${uuid}`,
            siteName: "TryZent AI Agents",
            locale: "en_US",
            images: [
                {
                    url: "/assets/bannerImage.png",
                    width: 1200,
                    height: 630,
                    alt: "Health Insurance Finder - AI-Powered Plan Recommendations",
                    type: "image/png",
                },
            ],
        },
        twitter: {
            card: "summary_large_image",
            site: "@tryzent",
            creator: "@tryzent",
            title: "AI Health Insurance Plan Recommendations",
            description: "Personalized insurance analysis with coverage comparison and cost breakdown.",
            images: ["/assets/bannerImage.png"],
        },
        alternates: {
            canonical: `https://agents.tryzent.com/share/health-insurance-finder/${uuid}`,
        },
        other: {
            "application-name": "TryZent Health Insurance Finder",
            "apple-mobile-web-app-title": "Health Insurance Finder",
            "apple-mobile-web-app-capable": "yes",
            "apple-mobile-web-app-status-bar-style": "default",
            "format-detection": "telephone=no",
            "mobile-web-app-capable": "yes",
            "msapplication-TileColor": "#4f46e5",
            "theme-color": "#4f46e5",
        },
    }
}

export default async function SharedHealthInsuranceFinderPage({ params }: Props) {
    const { uuid } = await params

    // Structured data for SEO
    const structuredData = {
        "@context": "https://schema.org",
        "@type": "Article",
        headline: "AI-Generated Health Insurance Plan Recommendations",
        description:
            "Personalized health insurance analysis with coverage comparison, cost breakdown, and expert recommendations tailored to individual needs and budget.",
        author: {
            "@type": "Organization",
            name: "TryZent",
            url: "https://agents.tryzent.com",
        },
        publisher: {
            "@type": "Organization",
            name: "TryZent",
            logo: {
                "@type": "ImageObject",
                url: "https://agents.tryzent.com/assets/logo-modified.png",
                width: 200,
                height: 200,
            },
        },
        datePublished: new Date().toISOString(),
        dateModified: new Date().toISOString(),
        mainEntityOfPage: {
            "@type": "WebPage",
            "@id": `https://agents.tryzent.com/share/health-insurance-finder/${uuid}`,
        },
        image: {
            "@type": "ImageObject",
            url: "https://agents.tryzent.com/assets/bannerImage.png",
            width: 1200,
            height: 630,
        },
        articleSection: "Health Insurance",
        keywords: "health insurance, AI recommendations, coverage analysis, insurance comparison, health plans",
        about: {
            "@type": "Thing",
            name: "Health Insurance Planning",
            description: "AI-powered health insurance plan analysis and recommendations",
        },
    }

    return (
        <>
            <Head>
                <script
                    type="application/ld+json"
                    dangerouslySetInnerHTML={{ __html: JSON.stringify(structuredData, null, 2) }}
                />
            </Head>

            <div className="min-h-screen bg-gray-50">
                <div className="max-w-4xl mx-auto px-4 py-8">
                    <div className="bg-white rounded-lg shadow-sm border border-gray-200 p-6">
                        <div className="text-center">
                            <div className="w-16 h-16 bg-indigo-100 rounded-full flex items-center justify-center mx-auto mb-4">
                                <Shield className="h-8 w-8 text-indigo-600" />
                            </div>
                            <h1 className="text-2xl font-bold text-gray-900 mb-2">Health Insurance Recommendations</h1>
                            <p className="text-gray-600 mb-6">AI-powered analysis of health insurance plans tailored to your needs</p>

                            <div className="bg-indigo-50 border border-indigo-200 rounded-lg p-4 mb-6">
                                <p className="text-indigo-800 text-sm">
                                    This shared report contains personalized health insurance recommendations. The analysis includes
                                    coverage comparison, cost breakdown, and eligibility information.
                                </p>
                            </div>

                            <div className="text-center">
                                <a
                                    href="/agents/health-insurance-finder"
                                    className="inline-flex items-center px-6 py-3 bg-indigo-600 text-white rounded-lg hover:bg-indigo-700 transition-colors"
                                >
                                    <Shield className="mr-2 h-5 w-5" />
                                    Create Your Own Analysis
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </>
    )
}

// Enable static generation for better SEO and performance
export const dynamic = "force-static"
export const revalidate = 3600 // Revalidate every hour
